// 40 Pre-written Random Responses for Prayer Requests
const prayerResponses = [
  "Prayers sent your way. You're stronger than you think.",
  "Holding you in my thoughts. You're not alone in this.",
  "Sending love and light. Everything will work out.",
  "You've got this. Believing in you.",
  "Peace be with you. Stay strong.",
  "Your courage inspires me. Praying for you.",
  "God is with you. Trust the process.",
  "Lifting you up in prayer. You will overcome.",
  "Your heart is heard. You matter.",
  "Sending healing energy your way.",
  "Keep the faith. Better days are coming.",
  "You are seen and loved. Don't give up.",
  "Prayers and good vibes headed your way.",
  "Your strength will carry you through.",
  "Believing in a positive outcome for you.",
  "Sending you comfort and hope.",
  "You deserve good things. Stay hopeful.",
  "Praying for clarity and peace for you.",
  "Your struggle is real, but so is your strength.",
  "Sending all the love and support I can.",
  "This too shall pass. You will get through this.",
  "Believing in you and your journey.",
  "May you find peace amidst the chaos.",
  "Rooting for you. You've got what it takes.",
  "Trusting that you'll find your way.",
  "Sending strength for every step forward.",
  "You are worthy of good things.",
  "Prayers for wisdom and guidance for you.",
  "Your resilience is beautiful. Keep going.",
  "Sending you hope and encouragement.",
  "May you find the answers you're seeking.",
  "You are enough. Trust yourself.",
  "Prayers for patience and peace.",
  "Your story matters. Keep writing it.",
  "Sending all my support and prayers.",
  "You will come out stronger on the other side.",
  "Believing in the best for your future.",
  "Prayers for your health and happiness.",
  "You've overcome before. You'll do it again.",
  "Sending you light in dark times."
];

// 40 Pre-written Random Responses for Confessions
const confessionResponses = [
  "Your secret is safe here. You're not alone.",
  "Thank you for trusting us with this. You're brave.",
  "Everyone makes mistakes. You're human.",
  "What matters is that you're here, being honest.",
  "Your vulnerability is powerful. Keep going.",
  "It takes courage to admit things. You've got this.",
  "No judgment here. Just compassion.",
  "You're not the only one who feels this way.",
  "Your truth matters. Thank you for sharing.",
  "Healing begins with honesty. You're doing great.",
  "Everyone has a past. Focus on your future.",
  "You're allowed to be imperfect.",
  "This doesn't define you. Your choices moving forward do.",
  "Thank you for your honesty. That takes guts.",
  "You're worthy of forgiveness—especially your own.",
  "What you're feeling is valid.",
  "You're not broken. You're human.",
  "This moment doesn't erase your goodness.",
  "Your past doesn't determine your future.",
  "Confession is the first step to peace.",
  "You deserve to release this burden.",
  "Being honest with yourself is strength.",
  "You're braver than you believe.",
  "Forgive yourself like you'd forgive a friend.",
  "Your honesty helps others feel less alone.",
  "You're not as bad as you think.",
  "Everyone stumbles. What matters is getting up.",
  "Your conscience shows your good heart.",
  "It's okay to not be okay. It's okay to grow.",
  "This admission is a sign of your strength.",
  "You deserve peace and self-compassion.",
  "Your truth is valid, and so are you.",
  "Healing comes through acceptance, not shame.",
  "You're learning and growing. That's what matters.",
  "Your struggles make you relatable, not broken.",
  "Thank you for the vulnerability. We see you.",
  "You're taking the right steps forward.",
  "Everyone has secrets. You're brave for sharing.",
  "Your heart knows the way. Trust it.",
  "You're worthy of grace and second chances."
];

function getRandomResponse(type) {
  const responses = type === 'prayer' ? prayerResponses : confessionResponses;
  return responses[Math.floor(Math.random() * responses.length)];
}